# Generated by Django 3.0.6 on 2020-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=50)),
                ('head0highlight', models.CharField(default='', max_length=500)),
                ('head0content', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=50)),
                ('head1content', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=50)),
                ('head2content', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('thumnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
